language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jtanabef5/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jtanabef5/docker-react npm run test